using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Orkeon.Generators;

/// <summary>
/// Incremental source generator factoring out the « typed dictionary wrapper + nested
/// Builder » template historically duplicated 64 times across the codebase (SML-004).
/// For every <c>partial class</c> marked with <c>[TypedDictionary(typeof(TValue))]</c>
/// it emits the mechanical plumbing — private constructor, <c>Empty</c>,
/// <c>CreateBuilder()</c>, optional <c>CreateBuilderFrom()</c>, and the nested
/// <c>Builder</c> shell (backing dictionary, generic <c>Add</c>, <c>Build()</c>) —
/// plus the bodies of the strongly typed partial <c>AddXxx</c> methods annotated with
/// <c>[DictionaryEntry]</c>. The hand-written public API (signatures, names,
/// namespaces) is preserved exactly: only boilerplate moves to generated code.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class TypedDictionaryGenerator : IIncrementalGenerator
{
    private const string TypedDictionaryAttributeName = "Orkeon.Generators.TypedDictionaryAttribute";
    private const string DictionaryEntryAttributeName = "Orkeon.Generators.DictionaryEntryAttribute";

    private static readonly SymbolDisplayFormat TypeFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
            .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    /// <inheritdoc />
    /// <remarks>
    /// The marker attributes are NOT injected via RegisterPostInitializationOutput:
    /// they are declared once in Orkeon.Domain (namespace <c>Orkeon.Generators</c>,
    /// internal + InternalsVisibleTo) because per-compilation copies would collide
    /// (CS0436) across the Domain → Application/Infrastructure IVT chain.
    /// </remarks>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<GeneratedFile> files = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                TypedDictionaryAttributeName,
                static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                static (ctx, _) => CreateFile(ctx))
            .Where(static file => file is not null)
            .Select(static (file, _) => file!);

        context.RegisterSourceOutput(files, static (spc, file) =>
            spc.AddSource(file.HintName, SourceText.From(file.Source, Encoding.UTF8)));
    }

    private static GeneratedFile? CreateFile(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        AttributeData attribute = context.Attributes[0];
        if (attribute.ConstructorArguments.Length != 1 ||
            attribute.ConstructorArguments[0].Value is not ITypeSymbol valueTypeSymbol)
        {
            return null;
        }

        bool cacheEmpty = GetNamedFlag(attribute, "CacheEmpty", defaultValue: false);
        bool emitEmpty = GetNamedFlag(attribute, "EmitEmpty", defaultValue: true);
        bool emitBuilderFrom = GetNamedFlag(attribute, "EmitBuilderFrom", defaultValue: false);
        bool emitGenericAdd = GetNamedFlag(attribute, "EmitGenericAdd", defaultValue: true);

        string className = classSymbol.Name;
        string? namespaceName = classSymbol.ContainingNamespace is { IsGlobalNamespace: false } ns
            ? ns.ToDisplayString()
            : null;

        // Derived wrappers (e.g. TrainingParametersBase descendants) chain the dictionary
        // to the base constructor; standalone wrappers own the backing field.
        bool hasBaseDictionary = classSymbol.BaseType is { SpecialType: not SpecialType.System_Object };

        string valueType = valueTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string immutableDictionary = $"global::System.Collections.Immutable.ImmutableDictionary<string, {valueType}>";
        string mutableDictionary = $"global::System.Collections.Generic.Dictionary<string, {valueType}>";

        var builder = new StringBuilder(4096);
        builder.Append("// <auto-generated/>\n");
        builder.Append("// Generated by Orkeon.Generators.TypedDictionaryGenerator (chantier R4.5 / SML-004).\n");
        builder.Append("#nullable enable\n\n");

        if (namespaceName is not null)
        {
            builder.Append("namespace ").Append(namespaceName).Append(";\n\n");
        }

        builder.Append(classSymbol.IsRecord ? "partial record " : "partial class ").Append(className).Append('\n');
        builder.Append("{\n");

        if (!hasBaseDictionary)
        {
            builder.Append("    private readonly ").Append(immutableDictionary).Append(" _items;\n\n");
        }

        // Private constructor.
        builder.Append("    private ").Append(className).Append('(').Append(immutableDictionary).Append(" items)");
        if (hasBaseDictionary)
        {
            builder.Append("\n        : base(items)\n    {\n    }\n\n");
        }
        else
        {
            builder.Append("\n    {\n        _items = items ?? ").Append(immutableDictionary).Append(".Empty;\n    }\n\n");
        }

        AppendEmptyAccessor(builder, className, immutableDictionary, emitEmpty, cacheEmpty);
        AppendBuilderFactories(builder, className, emitBuilderFrom, hasBaseDictionary);
        AppendBuilderType(builder, new BuilderEmitContext
        {
            ClassSymbol = classSymbol,
            ClassName = className,
            ValueType = valueType,
            MutableDictionary = mutableDictionary,
            ImmutableDictionary = immutableDictionary,
            EmitBuilderFrom = emitBuilderFrom,
            HasBaseDictionary = hasBaseDictionary,
            EmitGenericAdd = emitGenericAdd
        });

        builder.Append("}\n");

        string hintName = namespaceName is null
            ? $"{className}.TypedDictionary.g.cs"
            : $"{namespaceName}.{className}.TypedDictionary.g.cs";

        return new GeneratedFile(hintName, builder.ToString());
    }

    private static void AppendEmptyAccessor(
        StringBuilder builder, string className, string immutableDictionary, bool emitEmpty, bool cacheEmpty)
    {
        if (!emitEmpty)
        {
            return;
        }

        if (cacheEmpty)
        {
            builder.Append("    private static readonly ").Append(className).Append(" _empty = new(")
                   .Append(immutableDictionary).Append(".Empty);\n\n");
            AppendSummary(builder, 1, $"Gets an empty <see cref=\"{className}\"/> instance.");
            builder.Append("    public static ").Append(className).Append(" Empty => _empty;\n\n");
        }
        else
        {
            AppendSummary(builder, 1, $"Gets an empty <see cref=\"{className}\"/> instance.");
            builder.Append("    public static ").Append(className).Append(" Empty => new(")
                   .Append(immutableDictionary).Append(".Empty);\n\n");
        }
    }

    private static void AppendBuilderFactories(
        StringBuilder builder, string className, bool emitBuilderFrom, bool hasBaseDictionary)
    {
        AppendSummary(builder, 1, $"Creates a new empty builder for <see cref=\"{className}\"/>.");
        builder.Append("    /// <returns>A new <see cref=\"Builder\"/>.</returns>\n");
        builder.Append("    public static Builder CreateBuilder() => new Builder();\n\n");

        if (emitBuilderFrom && !hasBaseDictionary)
        {
            AppendSummary(builder, 1, $"Creates a builder pre-populated from an existing <see cref=\"{className}\"/>.");
            builder.Append("    /// <param name=\"existing\">The existing instance to start from.</param>\n");
            builder.Append("    /// <returns>A new <see cref=\"Builder\"/> seeded with the existing entries.</returns>\n");
            builder.Append("    public static Builder CreateBuilderFrom(").Append(className)
                   .Append(" existing) => new Builder(existing._items);\n\n");
        }
    }

    private static void AppendBuilderType(StringBuilder builder, BuilderEmitContext ctx)
    {
        string className = ctx.ClassName;
        string mutableDictionary = ctx.MutableDictionary;

        // Nested Builder shell.
        AppendSummary(builder, 1, $"Builder for constructing <see cref=\"{className}\"/> instances.");
        builder.Append("    public sealed partial class Builder\n    {\n");
        builder.Append("        private readonly ").Append(mutableDictionary).Append(" _items;\n\n");
        AppendSummary(builder, 2, "Initializes an empty builder.");
        builder.Append("        public Builder()\n        {\n            _items = new ")
               .Append(mutableDictionary).Append("();\n        }\n");

        if (ctx.EmitBuilderFrom && !ctx.HasBaseDictionary)
        {
            builder.Append('\n');
            builder.Append("        internal Builder(").Append(ctx.ImmutableDictionary).Append(" existing)\n");
            builder.Append("        {\n            _items = new ").Append(mutableDictionary)
                   .Append("(existing);\n        }\n");
        }

        // Strongly typed partial AddXxx implementations.
        foreach (EntryMethod entry in CollectEntryMethods(ctx.ClassSymbol))
        {
            builder.Append('\n');
            AppendEntryMethod(builder, entry, ctx.ValueType);
        }

        // Untyped Add.
        if (ctx.EmitGenericAdd)
        {
            builder.Append('\n');
            AppendSummary(builder, 2, "Adds an arbitrary key-value entry.");
            builder.Append("        /// <param name=\"key\">The entry key.</param>\n");
            builder.Append("        /// <param name=\"value\">The value.</param>\n");
            builder.Append("        /// <returns>This builder for chaining.</returns>\n");
            builder.Append("        public Builder Add(string key, object value)\n        {\n");
            builder.Append("            _items[key] = ").Append(ctx.ValueType).Append(".From(value);\n");
            builder.Append("            return this;\n        }\n");
        }

        // Build.
        builder.Append('\n');
        AppendSummary(builder, 2, $"Builds the <see cref=\"{className}\"/> instance.");
        builder.Append("        /// <returns>The built instance.</returns>\n");
        builder.Append("        public ").Append(className).Append(" Build()\n        {\n");
        builder.Append("            return new ").Append(className)
               .Append("(global::System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary(_items));\n");
        builder.Append("        }\n");

        builder.Append("    }\n");
    }

    private static IEnumerable<EntryMethod> CollectEntryMethods(INamedTypeSymbol classSymbol)
    {
        INamedTypeSymbol? builderType = classSymbol.GetTypeMembers()
            .FirstOrDefault(static t => t.Name == "Builder");
        if (builderType is null)
        {
            yield break;
        }

        IEnumerable<IMethodSymbol> methods = builderType.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(static m => m.MethodKind == MethodKind.Ordinary && m.IsPartialDefinition)
            .OrderBy(static m => m.DeclaringSyntaxReferences.Length > 0
                ? m.DeclaringSyntaxReferences[0].Span.Start
                : 0);

        foreach (IMethodSymbol method in methods)
        {
            AttributeData? entryAttribute = method.GetAttributes().FirstOrDefault(static a =>
                a.AttributeClass?.ToDisplayString() == DictionaryEntryAttributeName);
            if (entryAttribute is null || method.Parameters.Length == 0)
            {
                continue;
            }

            string? key = entryAttribute.ConstructorArguments.Length == 1
                ? entryAttribute.ConstructorArguments[0].Value as string
                : null;
            string factory = GetNamedString(entryAttribute, "Factory") ?? "From";

            // Pass-through entries need a key parameter distinct from the value parameter.
            if (key is null && method.Parameters.Length < 2)
            {
                continue;
            }

            yield return new EntryMethod(method, key, factory);
        }
    }

    private static void AppendEntryMethod(StringBuilder builder, EntryMethod entry, string valueType)
    {
        IMethodSymbol method = entry.Method;
        ImmutableArray<IParameterSymbol> parameters = method.Parameters;

        builder.Append("        public partial Builder ").Append(method.Name);

        if (method.TypeParameters.Length > 0)
        {
            builder.Append('<')
                   .Append(string.Join(", ", method.TypeParameters.Select(static tp => tp.Name)))
                   .Append('>');
        }

        builder.Append('(');
        builder.Append(string.Join(", ", parameters.Select(static p =>
            (p.IsParams ? "params " : "") + p.Type.ToDisplayString(TypeFormat) + " " + Identifier(p.Name))));
        builder.Append(')');

        foreach (ITypeParameterSymbol tp in method.TypeParameters)
        {
            string constraints = FormatConstraints(tp);
            if (constraints.Length > 0)
            {
                builder.Append(" where ").Append(tp.Name).Append(" : ").Append(constraints);
            }
        }

        builder.Append("\n        {\n");
        builder.Append("            _items[").Append(KeyExpression(entry.Key, parameters)).Append("] = ");

        string valueArgument = Identifier(parameters[parameters.Length - 1].Name);
        if (entry.Factory.Length == 0)
        {
            builder.Append(valueArgument);
        }
        else
        {
            builder.Append(valueType).Append('.').Append(entry.Factory).Append('(').Append(valueArgument).Append(')');
        }

        builder.Append(";\n            return this;\n        }\n");
    }

    private static string KeyExpression(string? key, ImmutableArray<IParameterSymbol> parameters)
    {
        if (key is null)
        {
            return Identifier(parameters[0].Name);
        }

        int placeholder = key.IndexOf('{');
        if (placeholder < 0)
        {
            return Quote(key);
        }

        // Format key: replace {N} placeholders with the matching parameter names.
        var interpolated = new StringBuilder("$\"", key.Length + 16);
        for (int i = 0; i < key.Length; i++)
        {
            char c = key[i];
            if (c == '{')
            {
                int end = key.IndexOf('}', i + 1);
                if (end > i && int.TryParse(key.Substring(i + 1, end - i - 1), out int index) &&
                    index >= 0 && index < parameters.Length)
                {
                    interpolated.Append('{').Append(Identifier(parameters[index].Name)).Append('}');
                    i = end;
                    continue;
                }

                interpolated.Append("{{");
            }
            else if (c == '}')
            {
                interpolated.Append("}}");
            }
            else
            {
                AppendEscaped(interpolated, c);
            }
        }

        interpolated.Append('"');
        return interpolated.ToString();
    }

    private static string FormatConstraints(ITypeParameterSymbol typeParameter)
    {
        var constraints = new List<string>(4);
        if (typeParameter.HasReferenceTypeConstraint)
        {
            constraints.Add("class");
        }

        if (typeParameter.HasValueTypeConstraint)
        {
            constraints.Add("struct");
        }

        if (typeParameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("unmanaged");
        }

        if (typeParameter.HasNotNullConstraint)
        {
            constraints.Add("notnull");
        }

        constraints.AddRange(typeParameter.ConstraintTypes.Select(static t => t.ToDisplayString(TypeFormat)));

        if (typeParameter.HasConstructorConstraint)
        {
            constraints.Add("new()");
        }

        return string.Join(", ", constraints);
    }

    private static void AppendSummary(StringBuilder builder, int indentLevel, string text)
    {
        string indent = indentLevel == 1 ? "    " : "        ";
        builder.Append(indent).Append("/// <summary>").Append(text).Append("</summary>\n");
    }

    private static string Identifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None &&
        SyntaxFacts.GetContextualKeywordKind(name) == SyntaxKind.None
            ? name
            : "@" + name;

    private static string Quote(string value)
    {
        var quoted = new StringBuilder("\"", value.Length + 8);
        foreach (char c in value)
        {
            AppendEscaped(quoted, c);
        }

        return quoted.Append('"').ToString();
    }

    private static void AppendEscaped(StringBuilder builder, char c)
    {
        switch (c)
        {
            case '\\':
                builder.Append("\\\\");
                break;
            case '"':
                builder.Append("\\\"");
                break;
            default:
                builder.Append(c);
                break;
        }
    }

    private static bool GetNamedFlag(AttributeData attribute, string name, bool defaultValue)
    {
        foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
        {
            if (argument.Key == name && argument.Value.Value is bool value)
            {
                return value;
            }
        }

        return defaultValue;
    }

    private static string? GetNamedString(AttributeData attribute, string name)
    {
        foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
        {
            if (argument.Key == name)
            {
                return argument.Value.Value as string;
            }
        }

        return null;
    }

    /// <summary>
    /// Cohesive set of values threaded through the Builder-type emission. Groups the wrapper's
    /// identity (symbol/name), the rendered dictionary type strings, and the emission flags so
    /// they travel as a single argument instead of a long parameter list.
    /// </summary>
    // Plain settable properties (not a positional record): the project targets
    // netstandard2.0, where init-only setters would require an IsExternalInit
    // polyfill, and a constructor would reintroduce the long parameter list (S107).
    private sealed class BuilderEmitContext
    {
        public INamedTypeSymbol ClassSymbol { get; set; } = null!;
        public string ClassName { get; set; } = "";
        public string ValueType { get; set; } = "";
        public string MutableDictionary { get; set; } = "";
        public string ImmutableDictionary { get; set; } = "";
        public bool EmitBuilderFrom { get; set; }
        public bool HasBaseDictionary { get; set; }
        public bool EmitGenericAdd { get; set; }
    }

    private sealed class EntryMethod
    {
        public EntryMethod(IMethodSymbol method, string? key, string factory)
        {
            Method = method;
            Key = key;
            Factory = factory;
        }

        public IMethodSymbol Method { get; }

        public string? Key { get; }

        public string Factory { get; }
    }

    private sealed class GeneratedFile : IEquatable<GeneratedFile>
    {
        public GeneratedFile(string hintName, string source)
        {
            HintName = hintName;
            Source = source;
        }

        public string HintName { get; }

        public string Source { get; }

        public bool Equals(GeneratedFile? other) =>
            other is not null && HintName == other.HintName && Source == other.Source;

        public override bool Equals(object? obj) => Equals(obj as GeneratedFile);

        public override int GetHashCode()
        {
            unchecked
            {
                return (HintName.GetHashCode() * 397) ^ Source.GetHashCode();
            }
        }
    }
}
