using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.Extensions.Logging;

namespace Orkeon.Examples.Interactive.InterviewSpecForge.Commands;

/// <summary>
/// Shared staging logic (D21) used by both ForgeCommand and ReplayCommand.
/// Copies the transcript and the previous round's outputs (topics, tasks,
/// glossary, sqlite memory db) into the current attempt's <c>input-stage/</c>
/// directory before the crew is kicked off; after a successful run, copies
/// the resulting collections back to the experiment root so the next round
/// picks them up.
/// </summary>
/// <remarks>
/// // EXCEPTION-BOOTSTRAP — physical filesystem operations performed before
/// the per-forge VFS is built and after it has been torn down. The crew
/// itself never touches paths outside <c>/input</c> and <c>/output</c>.
/// </remarks>
internal static class ForgeStaging
{
    public static void StageInputs(
        string transcriptPath,
        string stageDir,
        string roundsRoot,
        string currentRoundDir,
        string currentAttemptDir,
        ILogger logger)
    {
        Directory.CreateDirectory(stageDir);

        File.Copy(transcriptPath, Path.Combine(stageDir, "transcript.txt"), overwrite: true);

        var experimentRoot = Path.GetDirectoryName(roundsRoot.TrimEnd(Path.DirectorySeparatorChar))!;
        var topicsSrc = Path.Combine(experimentRoot, "topics");
        var tasksSrc = Path.Combine(experimentRoot, "tasks");
        var glossarySrc = Path.Combine(experimentRoot, "glossary");

        var topicsDst = Path.Combine(stageDir, "topics");
        var tasksDst = Path.Combine(stageDir, "tasks");
        var glossaryDst = Path.Combine(stageDir, "glossary");

        CopyTreeIfExists(topicsSrc, topicsDst, logger);
        CopyTreeIfExists(tasksSrc, tasksDst, logger);
        CopyTreeIfExists(glossarySrc, glossaryDst, logger);

        StageMemoryDb(experimentRoot, currentRoundDir, currentAttemptDir, stageDir, logger);
    }

    /// <summary>
    /// Post-process the freshly-written <c>outputs/tasks/_index.json</c> to enforce
    /// the D14 contract: <c>id_stable</c> is an immutable UUID (32-hex-no-dashes),
    /// generated by the runner — NOT by the agent (which hallucinates sequential
    /// hex strings). For each task in the output index:
    /// <list type="bullet">
    ///   <item>if the same slug existed in <c>input-stage/tasks/_index.json</c>,
    ///         re-attach the input's <c>id_stable</c> (immutability across rounds).</item>
    ///   <item>otherwise, generate a fresh <c>Guid.NewGuid().ToString("N")</c>.</item>
    /// </list>
    /// Propagates the (possibly rewritten) <c>id_stable</c> to every
    /// <c>outputs/tasks/&lt;slug&gt;.json</c> sidecar and the matching
    /// <c>outputs/tasks/&lt;slug&gt;.md</c> frontmatter line.
    /// </summary>
    /// <remarks>
    /// // EXCEPTION-BOOTSTRAP — physical filesystem post-processing on the
    /// per-attempt outputs after the per-forge VFS has been torn down.
    /// </remarks>
    public static void PostProcessTaskUuids(string outputDir, string stageDir, ILogger logger)
    {
        var outIndexPath = Path.Combine(outputDir, "tasks", "_index.json");
        if (!File.Exists(outIndexPath))
        {
            logger.LogDebug("No tasks/_index.json in outputs — skipping UUID post-processing");
            return;
        }

        Dictionary<string, string> existingIds = LoadExistingIdsBySlug(
            Path.Combine(stageDir, "tasks", "_index.json"), logger);

        JsonNode? outRoot;
        try
        {
            outRoot = JsonNode.Parse(File.ReadAllText(outIndexPath));
        }
        catch (JsonException ex)
        {
            logger.LogWarning(ex, "Output tasks/_index.json is malformed — skipping UUID post-processing");
            return;
        }
        if (outRoot is null) return;

        var outTasks = outRoot["tasks"] as JsonObject;
        if (outTasks is null)
        {
            logger.LogDebug("outputs/tasks/_index.json has no 'tasks' object — skipping");
            return;
        }

        int preserved = 0, regenerated = 0;
        foreach (var kvp in outTasks)
        {
            var slug = kvp.Key;
            var entry = kvp.Value as JsonObject;
            if (entry is null) continue;

            string finalId;
            if (existingIds.TryGetValue(slug, out var preservedId))
            {
                finalId = preservedId;
                preserved++;
            }
            else
            {
                finalId = Guid.NewGuid().ToString("N");
                regenerated++;
            }

            var oldId = entry["id_stable"]?.GetValue<string>();
            entry["id_stable"] = finalId;

            if (!string.Equals(oldId, finalId, StringComparison.Ordinal))
            {
                RewriteSidecarId(Path.Combine(outputDir, "tasks", $"{slug}.json"), finalId, logger);
                RewriteMarkdownFrontmatterId(Path.Combine(outputDir, "tasks", $"{slug}.md"), finalId, logger);
            }
        }

        File.WriteAllText(outIndexPath,
            outRoot.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));

        logger.LogInformation(
            "UUID post-processing: {Preserved} preserved from input, {Regenerated} regenerated", preserved, regenerated);
    }

    private static Dictionary<string, string> LoadExistingIdsBySlug(string inputIndexPath, ILogger logger)
    {
        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        if (!File.Exists(inputIndexPath)) return map;

        try
        {
            var doc = JsonNode.Parse(File.ReadAllText(inputIndexPath));
            if (doc?["tasks"] is not JsonObject tasks) return map;
            foreach (var kvp in tasks)
            {
                if (kvp.Value is not JsonObject entry) continue;
                var id = entry["id_stable"]?.GetValue<string>();
                if (!string.IsNullOrWhiteSpace(id))
                    map[kvp.Key] = id;
            }
        }
        catch (JsonException ex)
        {
            logger.LogWarning(ex, "Could not parse {Path} — assuming no existing IDs", inputIndexPath);
        }
        return map;
    }

    private static void RewriteSidecarId(string sidecarJsonPath, string id, ILogger logger)
    {
        if (!File.Exists(sidecarJsonPath)) return;
        try
        {
            var node = JsonNode.Parse(File.ReadAllText(sidecarJsonPath));
            if (node is JsonObject obj)
            {
                obj["id_stable"] = id;
                File.WriteAllText(sidecarJsonPath,
                    node.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));
            }
        }
        catch (JsonException ex)
        {
            logger.LogWarning(ex, "Could not rewrite id_stable in {Path}", sidecarJsonPath);
        }
    }

    private static void RewriteMarkdownFrontmatterId(string mdPath, string id, ILogger logger)
    {
        if (!File.Exists(mdPath)) return;
        try
        {
            var lines = File.ReadAllLines(mdPath);
            bool inFrontmatter = false;
            bool replaced = false;
            for (int i = 0; i < lines.Length; i++)
            {
                if (lines[i].TrimEnd() == "---")
                {
                    inFrontmatter = !inFrontmatter;
                    if (!inFrontmatter) break;
                    continue;
                }
                if (inFrontmatter && lines[i].TrimStart().StartsWith("id_stable:", StringComparison.Ordinal))
                {
                    var indent = lines[i][..(lines[i].IndexOf("id_stable:", StringComparison.Ordinal))];
                    lines[i] = $"{indent}id_stable: \"{id}\"";
                    replaced = true;
                    break;
                }
            }
            if (replaced)
                File.WriteAllText(mdPath, string.Join('\n', lines) + "\n");
        }
        catch (Exception ex) when (ex is IOException || ex is UnauthorizedAccessException)
        {
            logger.LogWarning(ex, "Could not rewrite frontmatter id_stable in {Path}", mdPath);
        }
    }

    public static void PersistOutputsToRoot(string outputDir, TranscriptsCatalog catalog, ILogger logger)
    {
        var topicsOut = Path.Combine(outputDir, "topics");
        var tasksOut = Path.Combine(outputDir, "tasks");
        var glossaryOut = Path.Combine(outputDir, "glossary");

        if (Directory.Exists(topicsOut))
            MergeTreeOver(topicsOut, catalog.TopicsRoot, logger);
        if (Directory.Exists(tasksOut))
            MergeTreeOver(tasksOut, catalog.TasksRoot, logger);
        if (Directory.Exists(glossaryOut))
            MergeTreeOver(glossaryOut, catalog.GlossaryRoot, logger);

        Directory.CreateDirectory(catalog.SummariesRoot);
        Directory.CreateDirectory(catalog.ReportsRoot);
        foreach (var f in Directory.EnumerateFiles(outputDir, "*--summary.*"))
            File.Copy(f, Path.Combine(catalog.SummariesRoot, Path.GetFileName(f)), overwrite: true);
        foreach (var f in Directory.EnumerateFiles(outputDir, "*--cr.*"))
            File.Copy(f, Path.Combine(catalog.ReportsRoot, Path.GetFileName(f)), overwrite: true);
    }

    private static void CopyTreeIfExists(string sourceDir, string destDir, ILogger logger)
    {
        if (!Directory.Exists(sourceDir))
        {
            logger.LogDebug("Source {Source} does not exist — skipping copy", sourceDir);
            return;
        }
        Directory.CreateDirectory(destDir);
        foreach (var file in Directory.EnumerateFiles(sourceDir, "*", SearchOption.AllDirectories))
        {
            var rel = Path.GetRelativePath(sourceDir, file);
            if (string.Equals(rel, ".gitkeep", StringComparison.OrdinalIgnoreCase))
                continue;
            var dst = Path.Combine(destDir, rel);
            Directory.CreateDirectory(Path.GetDirectoryName(dst)!);
            File.Copy(file, dst, overwrite: true);
        }
    }

    private static void MergeTreeOver(string sourceDir, string destDir, ILogger logger)
    {
        Directory.CreateDirectory(destDir);
        foreach (var file in Directory.EnumerateFiles(sourceDir, "*", SearchOption.AllDirectories))
        {
            var rel = Path.GetRelativePath(sourceDir, file);
            var dst = Path.Combine(destDir, rel);
            Directory.CreateDirectory(Path.GetDirectoryName(dst)!);
            File.Copy(file, dst, overwrite: true);
        }
    }

    /// <summary>
    /// Stage the Sqlite memory database (D20) for semantic continuity across rounds.
    /// We look for the most recent attempt's logs/memory.db (or the experiment-wide
    /// memory.db) and copy it into the stage dir so the crew can read it; the new
    /// round will write its updated version back via the output mount if the
    /// EncryptedMemoryProviderDecorator points to /output. In V1 we accept the cost
    /// of re-embedding on memory absence — the file is informational.
    /// </summary>
    private static void StageMemoryDb(string experimentRoot, string currentRoundDir, string currentAttemptDir, string stageDir, ILogger logger)
    {
        var canonicalDb = Path.Combine(experimentRoot, "memory.db");
        if (File.Exists(canonicalDb))
        {
            File.Copy(canonicalDb, Path.Combine(stageDir, "memory.db"), overwrite: true);
            logger.LogInformation("Staged memory.db from {Path}", canonicalDb);
            return;
        }
        logger.LogDebug("No previous memory.db found at {Path} — crew will start memory cold", canonicalDb);
    }
}
