using CommandLine;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Orkeon.Domain.Common;
using Orkeon.Domain.FileSystem;
using Orkeon.Domain.SharedKernel;
using Orkeon.Hosting;
using Orkeon.Infrastructure.LLMs;
using Orkeon.Studio.Core.Configuration;
using Orkeon.Studio.Core.FileSystem;
using Orkeon.Studio.Core.Forge;
using Orkeon.Studio.Core.Launch;
using Orkeon.Studio.Core.Profiles;
using Orkeon.Studio.Core.Storage;
using Orkeon.Studio.Core.Teams;

namespace Orkeon.Studio.Core.Tests.Teams;

/// <summary>
/// STUDIO-50: a scheduled team runs as Studio launches it. The operating system runs a team's
/// <c>run.cmd</c>/<c>run.sh</c> (STUDIO-27), so Studio writes them again from the companion file
/// (<c>studio-team.json</c>): the team's model setting as <c>--llm-profile</c> — the host profile
/// that setting is in the settings file (STUDIO-48) — and its folders as Studio launches them
/// (<see cref="LaunchMountPlan"/>), the team's own anchored to the launcher's folder. Never a key.
/// </summary>
public sealed class TeamLaunchersTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "orkeon-team-launchers-" + Guid.NewGuid().ToString("N"));
    private readonly string _team;
    private readonly string _settingsPath;

    private static readonly MountId Docs = MountId.Create();

    private static readonly ModelProfile DeepSeek = new()
    {
        Name = "DeepSeek", Provider = "DeepSeek", BaseUrl = "https://api.deepseek.com",
        Model = "deepseek-v4-flash", KeyEnvName = "DEEPSEEK_API_KEY", TimeoutSeconds = 600,
    };

    private static readonly ModelProfile Zai = new()
    {
        Name = "Z.AI", Provider = "Z.AI", BaseUrl = "https://api.z.ai/api/paas/v4",
        Model = "glm-5.2", KeyEnvName = "ZAI_API_KEY",
    };

    /// <summary>The « no model » card: a setting that names no provider is offered to no crew.</summary>
    private static readonly ModelProfile NoModel = new() { Name = "Aucun" };

    private static readonly ModelProfileSet Settings =
        ModelProfileSet.Empty.Upsert(DeepSeek).Upsert(Zai).Upsert(NoModel);

    public TeamLaunchersTests()
    {
        _team = Path.Combine(_root, "teams", "veille-docs");
        Directory.CreateDirectory(Path.Combine(_team, "crew"));
        File.WriteAllText(Path.Combine(_team, "crew", "config.yaml"), "name: veille\n");
        // What `forge promote` wrote: Studio writes them again.
        File.WriteAllText(Path.Combine(_team, TeamLaunchers.PosixLauncherName), "#!/usr/bin/env sh\nexec orkeon run \"$DIR/crew\"\n");
        File.WriteAllText(Path.Combine(_team, TeamLaunchers.WindowsLauncherName), "@echo off\r\norkeon run \"%~dp0crew\"\r\n");
        File.WriteAllText(Path.Combine(_team, ForgeSessionCatalog.TeamRecordFileName), """
            {"v":1,"id":"6f1c2a0e-4b7d-4e9a-9f53-1d2c3b4a5e6f","slug":"veille","title":"Veille","format":"yaml",
             "promotedAt":"2026-08-19T08:00:00Z",
             "brief":{"need":"n","language":"fr",
                      "sample":{"variables":{"supplier_url":"https://exemple.fr/offres","seuil":"10%"},"initialContext":"Premier essai"}}}
            """);
        _settingsPath = Path.Combine(_root, AppSettingsDocument.FileName);
        File.WriteAllText(_settingsPath, "{}");
    }

    public void Dispose()
    {
        try { Directory.Delete(_root, recursive: true); } catch (IOException) { /* best-effort */ }
    }

    private void Adopt(string? setting, params string[] mounts) =>
        TeamCatalog.SaveMetadata(_team, new StudioTeamMetadata
        {
            Name = "Veille docs",
            Profile = setting,
            Mounts = mounts.Length > 0 ? mounts : null,
        });

    private TeamLauncherContext Context(IReadOnlyList<string>? declared = null) => new()
    {
        Profiles = Settings,
        DeclaredMounts = declared ?? [$"{Docs}|/data/docs:/docs:ro"],
        SettingsPath = _settingsPath,
    };

    private string Posix() => File.ReadAllText(Path.Combine(_team, TeamLaunchers.PosixLauncherName));

    private string Windows() => File.ReadAllText(Path.Combine(_team, TeamLaunchers.WindowsLauncherName));

    [Fact]
    public void The_launchers_carry_the_setting_and_the_folders_of_the_companion_file_and_no_key()
    {
        Adopt("Z.AI", "./output:/output:rw", "./input:/workspace:ro", $"{Docs}|/data/docs:/docs:ro");

        Assert.True(TeamLaunchers.Regenerate(_team, Context()));

        var posix = Posix();
        Assert.StartsWith("#!/usr/bin/env sh\n# Generated by Orkeon Forge for the team 'veille-docs'.\n", posix, StringComparison.Ordinal);
        Assert.Contains("Orkeon Studio writes this file again", posix, StringComparison.Ordinal);
        Assert.Contains("cd \"$DIR\" || exit 1\nexec orkeon \\\n  run \"$DIR/crew\" \\\n", posix, StringComparison.Ordinal);
        Assert.Contains($"  --settings '{_settingsPath}' \\\n", posix, StringComparison.Ordinal);
        Assert.Contains("  --llm-profile 'z-ai' \\\n", posix, StringComparison.Ordinal);
        Assert.Contains("  --mount \"\\\"$DIR/output\\\":/output:rw\" \"\\\"$DIR/input\\\":/workspace:ro\" \\\n", posix, StringComparison.Ordinal);
        Assert.Contains($"  --mount-id '{Docs}' \\\n", posix, StringComparison.Ordinal);
        Assert.Contains("  --var 'supplier_url=https://exemple.fr/offres' 'seuil=10%' \\\n", posix, StringComparison.Ordinal);
        Assert.EndsWith("  --initial-context 'Premier essai'\n", posix, StringComparison.Ordinal);

        var windows = Windows();
        Assert.StartsWith("@echo off\r\nrem Generated by Orkeon Forge for the team 'veille-docs'.\r\n", windows, StringComparison.Ordinal);
        Assert.Contains("cd /d \"%~dp0\" || exit /b 1\r\norkeon run \"%~dp0crew\"", windows, StringComparison.Ordinal);
        Assert.Contains(" --llm-profile \"z-ai\"", windows, StringComparison.Ordinal);
        Assert.Contains(" --mount \"\\\"%~dp0output\\\":/output:rw\" \"\\\"%~dp0input\\\":/workspace:ro\"", windows, StringComparison.Ordinal);
        Assert.Contains($" --mount-id \"{Docs}\"", windows, StringComparison.Ordinal);
        // A '%' is doubled: cmd expands what it reads between two of them, even inside quotes.
        Assert.Contains(" --var \"supplier_url=https://exemple.fr/offres\" \"seuil=10%%\"", windows, StringComparison.Ordinal);
        Assert.EndsWith(" --initial-context \"Premier essai\"\r\n", windows, StringComparison.Ordinal);

        foreach (var launcher in new[] { posix, windows })
        {
            Assert.DoesNotContain("ApiKey", launcher, StringComparison.Ordinal);
            Assert.DoesNotContain("ZAI_API_KEY", launcher, StringComparison.Ordinal);
            Assert.DoesNotContain("ORKEON_Llm", launcher, StringComparison.Ordinal);
        }

        if (!OperatingSystem.IsWindows())
            Assert.True(File.GetUnixFileMode(Path.Combine(_team, TeamLaunchers.PosixLauncherName)).HasFlag(UnixFileMode.UserExecute));
    }

    [Fact]
    public void The_folders_go_as_a_studio_launch_passes_them()
    {
        var copy = Path.Combine(_root, "elsewhere");
        var unknown = MountId.Create();
        Adopt(null, "./output:/output:rw", $"{Docs}|/data/docs:/docs:ro", $"{copy}:/archive:ro", $"{unknown}|/x:/y:ro");

        var launch = TeamLaunchers.Describe(_team, Context())!;

        // The same arguments a Studio launch passes (LaunchMountPlan) — the team's own folder
        // anchored to the launcher's folder, which keeps the team relocatable —, and an id this
        // machine does not declare passed on: the runner refuses it at start, as Studio refuses
        // to launch the team.
        var plan = LaunchMountPlan.For(TeamCatalog.Describe(_team, Context().DeclaredMounts).ResolvedMounts);
        Assert.Equal([.. plan.MountIds, .. plan.UnknownIds], launch.MountIds);
        Assert.Equal(2, launch.Mounts.Count);
        Assert.Equal("output", launch.Mounts[0].TeamFolder);
        Assert.Equal(":/output:rw", launch.Mounts[0].Tail);
        Assert.Null(launch.Mounts[1].TeamFolder);
        Assert.Equal(plan.Mounts[1], launch.Mounts[1].Literal);
        Assert.Null(launch.LlmProfile);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("Ancien réglage")]
    [InlineData("Aucun")]
    public void A_team_on_no_setting_or_on_one_offered_to_no_crew_runs_on_the_default(string? setting)
    {
        Adopt(setting, "./output:/output:rw");

        Assert.True(TeamLaunchers.Regenerate(_team, Context()));

        Assert.DoesNotContain("--llm-profile", Posix(), StringComparison.Ordinal);
        Assert.DoesNotContain("--llm-profile", Windows(), StringComparison.Ordinal);
    }

    [Fact]
    public void The_team_on_the_elected_setting_still_names_it_so_a_new_election_does_not_move_it()
    {
        Adopt("DeepSeek");

        TeamLaunchers.Regenerate(_team, Context());

        Assert.Contains("--llm-profile 'deepseek'", Posix(), StringComparison.Ordinal);
    }

    [Fact]
    public void A_settings_file_that_does_not_exist_is_not_named_the_run_resolves_its_own()
    {
        Adopt("Z.AI");

        TeamLaunchers.Regenerate(_team, Context() with { SettingsPath = Path.Combine(_root, "absent.json") });

        Assert.DoesNotContain("--settings", Posix(), StringComparison.Ordinal);
        Assert.DoesNotContain("--settings", Windows(), StringComparison.Ordinal);
    }

    [Fact]
    public void A_script_team_runs_its_crew_script_and_carries_no_sample_inputs()
    {
        File.WriteAllText(Path.Combine(_team, ForgeSessionCatalog.TeamRecordFileName), """
            {"v":1,"slug":"veille","format":"script","brief":{"sample":{"variables":{"a":"1"}}}}
            """);
        File.WriteAllText(Path.Combine(_team, "crew", "crew.ork.ts"), "// crew\n");
        Adopt("Z.AI");

        TeamLaunchers.Regenerate(_team, Context());

        var posix = Posix();
        Assert.Contains("run \"$DIR/crew/crew.ork.ts\"", posix, StringComparison.Ordinal);
        Assert.Contains("crew/crew.ork.ts", posix, StringComparison.Ordinal);
        Assert.DoesNotContain("--var", posix, StringComparison.Ordinal);
        Assert.Contains("run \"%~dp0crew/crew.ork.ts\"", Windows(), StringComparison.Ordinal);
    }

    [Fact]
    public void Hand_edits_are_replaced_whole_and_a_launcher_already_right_is_left_as_it_is()
    {
        Adopt("Z.AI", "./output:/output:rw");
        File.WriteAllText(Path.Combine(_team, TeamLaunchers.PosixLauncherName), "#!/usr/bin/env sh\necho edited by hand\n");

        Assert.True(TeamLaunchers.Regenerate(_team, Context()));
        var written = Posix();
        Assert.DoesNotContain("edited by hand", written, StringComparison.Ordinal);
        var stamp = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        File.SetLastWriteTimeUtc(Path.Combine(_team, TeamLaunchers.PosixLauncherName), stamp);

        Assert.True(TeamLaunchers.Regenerate(_team, Context()));
        Assert.Equal(written, Posix());
        Assert.Equal(stamp, File.GetLastWriteTimeUtc(Path.Combine(_team, TeamLaunchers.PosixLauncherName)));
    }

    [Fact]
    public void A_folder_that_holds_no_promoted_team_gets_no_launcher()
    {
        var handBuilt = Path.Combine(_root, "teams", "faite-main");
        Directory.CreateDirectory(handBuilt);
        File.WriteAllText(Path.Combine(handBuilt, "crew.yaml"), "name: x\n");
        TeamCatalog.SaveMetadata(handBuilt, new StudioTeamMetadata { Profile = "Z.AI" });

        Assert.False(TeamLaunchers.Regenerate(handBuilt, Context()));
        Assert.False(File.Exists(Path.Combine(handBuilt, TeamLaunchers.PosixLauncherName)));
        Assert.False(File.Exists(Path.Combine(handBuilt, TeamLaunchers.WindowsLauncherName)));
        Assert.False(TeamLaunchers.Regenerate(Path.Combine(_root, "nulle-part"), Context()));

        // A promoted folder without a companion file keeps what the engine wrote.
        var engineOnly = File.ReadAllText(Path.Combine(_team, TeamLaunchers.PosixLauncherName));
        Assert.False(TeamLaunchers.Regenerate(_team, Context()));
        Assert.Equal(engineOnly, Posix());
    }

    /// <summary>
    /// The drift pin against the runner itself: the <c>run.sh</c> Studio writes, run by a real
    /// shell over a stub <c>orkeon</c>, hands the runner arguments its own grammar
    /// (<see cref="RunnerOptionsBase"/>) parses — and the run they describe, built by the real
    /// runner host over the settings file Studio wrote, runs on the team's setting.
    /// </summary>
    [Fact]
    [Trait("Category", "Integration")]
    public async Task The_posix_launcher_survives_the_shell_and_runs_on_the_teams_setting_with_its_folders()
    {
        Assert.SkipWhen(OperatingSystem.IsWindows() || !File.Exists("/bin/sh"), "The POSIX launcher needs a POSIX shell at /bin/sh.");

        var document = AppSettingsDocument.Parse("""{ "RaggableTree": { "Enabled": false } }""");
        HostLlmProfiles.Mirror(document, ModelProfileSet.Empty, Settings);
        HostLlmProfiles.ElectDefault(document, Settings.Default!);
        document.Mounts.Add(new MountDefinition { Id = Docs, PhysicalPath = Path.Combine(_root, "docs"), VirtualPath = "/docs", Rights = MountRights.ReadOnly });
        Directory.CreateDirectory(Path.Combine(_root, "docs"));
        await AppSettingsFile.SaveAsync(document, _settingsPath, TestContext.Current.CancellationToken);
        Adopt("Z.AI", "./output:/output:rw", $"{Docs}|{Path.Combine(_root, "docs")}:/docs:ro");

        Assert.True(TeamLaunchers.Regenerate(_team, Context(document.Mounts.RawEntries)));
        var argv = RunThroughShell(Path.Combine(_team, TeamLaunchers.PosixLauncherName));

        Assert.Equal(["run", Path.Combine(_team, "crew")], argv.Take(2));
        using var parser = new Parser(s => s.HelpWriter = null);
        var options = Assert.IsType<Parsed<LauncherOptions>>(parser.ParseArguments<LauncherOptions>(argv.Skip(2))).Value;
        Assert.Equal(_settingsPath, options.SettingsPath);
        Assert.Equal("z-ai", options.LlmProfile);
        Assert.Equal([Docs.ToString()], options.MountIds);
        Assert.Equal(["supplier_url=https://exemple.fr/offres", "seuil=10%"], options.Variables);
        Assert.Equal("Premier essai", options.InitialContext);
        var output = FileSystemMount.Parse(Assert.Single(options.Mounts));
        Assert.Equal(Path.Combine(_team, "output"), Path.TrimEndingDirectorySeparator(output.BasePath));
        Assert.Equal("/output", output.VirtualPath);

        // The runner host the scheduled run builds: the team's setting is its default, the
        // elected one of the settings (DeepSeek) is not.
        Directory.CreateDirectory(Path.Combine(_team, "output"));
        using var host = RunnerHost.Build(
            options.SettingsPath,
            new RunnerMountPlan { CliMounts = [.. options.Mounts], SelectedMountIds = [Docs], AllowExternalMounts = true },
            configureLogging: (_, logging) => logging.SetMinimumLevel(LogLevel.None),
            llmProfile: options.LlmProfile);
        var provider = MeteredLlmProvider.Unwrap(host.Services.GetRequiredService<ILlmProvider>());
        Assert.IsType<ZaiLlmProvider>(provider);
        Assert.Equal("glm-5.2", provider.BaseConfig!.Model);
        Assert.Equal(new Uri("https://api.z.ai/api/paas/v4"), provider.BaseConfig.BaseUrl);
    }

    /// <summary>The runner's own option grammar, as a parser target.</summary>
    private sealed class LauncherOptions : RunnerOptionsBase;

    /// <summary>
    /// Runs a launcher with a stub <c>orkeon</c> on PATH that prints one argument per line, and
    /// returns the argument vector the real CLI would have received — the CLI's own pin
    /// (<c>ForgePromoteTests.RunThroughShell</c>), on the launcher Studio writes.
    /// </summary>
    private List<string> RunThroughShell(string launcherPath)
    {
        var binDir = Path.Combine(_root, "stub-bin");
        Directory.CreateDirectory(binDir);
        var stub = Path.Combine(binDir, "orkeon");
        File.WriteAllText(stub, "#!/usr/bin/env sh\nfor a in \"$@\"; do printf '%s\\n' \"$a\"; done\n");
        if (!OperatingSystem.IsWindows())
            File.SetUnixFileMode(stub, UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute);

        var startInfo = new System.Diagnostics.ProcessStartInfo("/bin/sh")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        startInfo.ArgumentList.Add(launcherPath);
        startInfo.Environment["PATH"] = binDir + Path.PathSeparator + Environment.GetEnvironmentVariable("PATH");

        using var process = System.Diagnostics.Process.Start(startInfo)!;
        var stdout = process.StandardOutput.ReadToEnd();
        var stderr = process.StandardError.ReadToEnd();
        process.WaitForExit();

        Assert.True(process.ExitCode == 0, $"launcher exited {process.ExitCode}: {stderr}");
        return [.. stdout.Split('\n', StringSplitOptions.RemoveEmptyEntries)];
    }
}
