using DomainAgent = Orkeon.Domain.Agent.Agent;

namespace Orkeon.Scripting.Builders;

/// <summary>
/// Wrapper exposed to JS for an agent built by <see cref="JsAgentBuilder"/>. Exposes the
/// human-readable <c>name</c> and the auto-generated ULID <c>id</c>. Behaviour pieces
/// (body, hooks, state factory) are captured here for the runtime to invoke during
/// <c>crew.run</c>; that wiring lands in SCR-04 and SCR-08.
/// </summary>
#pragma warning disable IDE1006 // Property names match the JS surface
#pragma warning disable CS1591
public sealed class JsAgent
{
    /// <summary>Human-readable name supplied by the script (<c>agentBuilder().name(...)</c>).</summary>
    public string name { get; }

    /// <summary>ULID-formatted identifier generated by the domain layer (26 chars).</summary>
    public string id { get; }

    /// <summary>Underlying domain aggregate (not exposed to scripts).</summary>
    internal DomainAgent Domain { get; }

    /// <summary>Captured builder state (body, hooks, state factory, etc.).</summary>
    internal JsAgentBuilder Builder { get; }

    /// <summary>
    /// <c>onCommand</c> handlers declared on this agent (design §8 item 9). Public so the host
    /// command-dispatch layer (a different assembly) can wire them onto <c>IAgentChannel</c>.
    /// </summary>
    public IReadOnlyList<AgentCommandHandler> CommandHandlers => Builder.OnCommandHandlers;

    /// <summary>
    /// Current crew the agent is attached to, or <c>null</c> when detached.
    /// V1 enforces mono-crew: an agent can join only one crew at a time. After
    /// <c>crew.remove(agent)</c> the slot is cleared and the agent can be re-attached
    /// to another crew.
    /// </summary>
    internal Orkeon.Scripting.Runtime.JsCrew? CurrentCrew { get; set; }

    internal JsAgent(string name, DomainAgent domain, JsAgentBuilder builder)
    {
        this.name = name;
        id = domain.Id.Value.ToString();
        Domain = domain;
        Builder = builder;
    }
}
#pragma warning restore CS1591
#pragma warning restore IDE1006
