#!/usr/bin/env python3
"""Insert / refresh a canonical "Run it" section in every numbered example README.

Item P1-3 (rollout): each numbered example under ``examples/0N-*/NN-name/`` gets a
standard, copy-pasteable launch section:

  * the exact ``dotnet run`` command (correct runner + real config path),
  * a pointer to the appsettings LLM profiles and the getting-started guide,
  * a note about the example-data policy.

Design goals
------------
* **Idempotent** — the generated block is wrapped in sentinel comments; a second run
  regenerates an identical block and rewrites nothing.
* **Non-destructive** — a *simple* existing ``## Run`` section (a single standard/trading
  ``dotnet run`` command) is upgraded in place; a *curated* run section (mounts, ``###``
  sub-steps, or a non-default runner such as the interactive or ConsoleApp runners) is left
  untouched and reported so it can be handled by hand.
* **Language-aware** — French READMEs get a ``## Lancer`` section, English ones ``## Run it``.

The 10 "vitrine" (showcase) examples are excluded — they are curated by hand in parallel.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# --- Configuration ----------------------------------------------------------------------

# Repository root is the parent of this script's directory (scripts/).
REPO_ROOT = Path(__file__).resolve().parent.parent
EXAMPLES_ROOT = REPO_ROOT / "examples"

# The 10 showcase examples, curated by hand — never touched by this script.
VITRINES = {
    "01-enterprise/01-research-assistant",
    "02-science-research/19-experimental-data",
    "03-finance-trading/34-portfolio-consensus",
    "03-finance-trading/40-invoice-processing",
    "04-health-wellness/47-nutrition-planner",
    "05-education/63-skills-gap-mapping",
    "06-engineering-devops/71-cloud-audit-nist",
    "07-creative-media/78-synthetic-data",
    "08-iot-smart-systems/87-fleet-management",
    "09-experimental/97-multi-party-negotiation",
}

BEGIN_MARK = "<!-- BEGIN run-it (auto-generated by scripts/add-readme-run-section.py — edit the script, not this block) -->"
END_MARK = "<!-- END run-it (auto-generated by scripts/add-readme-run-section.py — edit the script, not this block) -->"

# Headers (any language / casing) that denote an existing launch section.
RUN_HEADER_RE = re.compile(
    r"^##\s+(Run it|Run|Running|Lancer|Ex[eé]cuter|Comment lancer)\b.*$",
    re.IGNORECASE,
)
H2_RE = re.compile(r"^##\s+\S")
H1_RE = re.compile(r"^#\s+\S")

# French body markers — used to pick FR vs EN wording.
FR_MARKERS = [
    r"\bd[ée]montre\b",
    r"cet exemple",
    r"responsabilit[ée]s",
    r"outils natifs",
    r"points de montage",
    r"\bretenu\b",
    r"\bg[èe]re\b",
    r"pr[ée]requis\b",
    r"^##\s+Lancer\b",
    r"^##\s+Ex[ée]cuter\b",
]
FR_MARKER_RE = re.compile("|".join(FR_MARKERS), re.IGNORECASE | re.MULTILINE)


@dataclass
class Result:
    modified: list[str] = field(default_factory=list)
    inserted_new: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    special_skipped: list[tuple[str, str]] = field(default_factory=list)
    vitrine_skipped: list[str] = field(default_factory=list)


# --- Helpers ----------------------------------------------------------------------------


def rel_example(readme: Path) -> str:
    """`examples/03-finance-trading/31-algo-trading/README.md` -> `03-finance-trading/31-algo-trading`."""
    return readme.parent.relative_to(EXAMPLES_ROOT).as_posix()


def runner_for(rel: str) -> str:
    return "trading" if rel.startswith("03-finance-trading/") else "standard"


def is_french(text: str) -> bool:
    return len(FR_MARKER_RE.findall(text)) >= 2


def build_block(rel: str, french: bool) -> str:
    """The canonical Run-it block, sentinel-wrapped, including its own H2 header."""
    runner = runner_for(rel)
    command = (
        "```bash\n"
        f"dotnet run --project examples/runners/{runner} -- \\\n"
        f"  --config examples/{rel}/config.yaml \\\n"
        "  --settings examples/appsettings/appsettings.deepseek.local.json\n"
        "```"
    )
    if french:
        body = (
            "## Lancer\n\n"
            f"{BEGIN_MARK}\n"
            "Depuis la racine du dépôt :\n\n"
            f"{command}\n\n"
            "**Profil LLM** — le fichier passé à `--settings` ci-dessus est l'un des profils prêts à "
            "l'emploi de [`examples/appsettings/`](../../appsettings/README.md). Copiez un gabarit "
            "`*.example` (retirez le suffixe `.example`) et ajoutez votre clé, ou pointez `--settings` "
            "vers n'importe quel autre profil (OpenAI, GLM, Docker Model Runner local). Première fois ? "
            "Voir [Lancer votre premier exemple](../../../docs/getting-started/run-your-first-example.md).\n\n"
            "**Données** — cet exemple ne fournit pas encore de données d'exemple ; voir "
            "[docs/reference/example-data-policy.md](../../../docs/reference/example-data-policy.md).\n"
            f"{END_MARK}"
        )
    else:
        body = (
            "## Run it\n\n"
            f"{BEGIN_MARK}\n"
            "From the repository root:\n\n"
            f"{command}\n\n"
            "**LLM profile** — the file passed to `--settings` above is one of the ready-made profiles "
            "in [`examples/appsettings/`](../../appsettings/README.md). Copy a `*.example` template "
            "(drop the `.example` suffix) and add your key, or point `--settings` at any other profile "
            "(OpenAI, GLM, local Docker Model Runner). First run? See "
            "[Run your first example](../../../docs/getting-started/run-your-first-example.md).\n\n"
            "**Data** — this example does not ship sample data yet; see "
            "[docs/reference/example-data-policy.md](../../../docs/reference/example-data-policy.md).\n"
            f"{END_MARK}"
        )
    return body


def find_section_span(lines: list[str], header_idx: int) -> int:
    """Return the exclusive end index of the section starting at header_idx (next H2 / EOF)."""
    for i in range(header_idx + 1, len(lines)):
        if H2_RE.match(lines[i]):
            return i
    return len(lines)


def section_is_curated(section_lines: list[str], runner: str) -> bool:
    """A run section we must NOT overwrite: mounts, sub-steps, or a non-default runner."""
    text = "\n".join(section_lines)
    if "--mount" in text:
        return True
    if any(re.match(r"^###\s+\S", ln) for ln in section_lines):
        return True
    if "runners/interactive" in text or "src/apps" in text:
        return True
    # References a different examples/runners/<x> than the category default.
    for m in re.finditer(r"examples/runners/([\w-]+)", text):
        if m.group(1) != runner:
            return True
    # Has no launch command at all -> treat as curated/ambiguous, don't clobber.
    if "dotnet run" not in text:
        return True
    return False


def intro_insert_idx(lines: list[str]) -> int:
    """Index of the first H2 (insert the block just before it); EOF if none."""
    for i, ln in enumerate(lines):
        if H2_RE.match(ln):
            return i
    return len(lines)


def process(readme: Path, result: Result, write: bool) -> None:
    rel = rel_example(readme)
    if rel in VITRINES:
        result.vitrine_skipped.append(rel)
        return

    original = readme.read_text(encoding="utf-8")
    french = is_french(original)
    block = build_block(rel, french)

    # 1) Already generated -> regenerate in place (idempotent).
    if BEGIN_MARK in original and END_MARK in original:
        # Replace from the section header (## Run it / ## Lancer) preceding BEGIN, through END.
        pattern = re.compile(
            r"^##\s+(?:Run it|Lancer)\b.*?\n"
            + re.escape(BEGIN_MARK)
            + r".*?"
            + re.escape(END_MARK),
            re.DOTALL | re.MULTILINE,
        )
        new_text, n = pattern.subn(block, original)
        if n == 0:
            # Marker present without a recognizable header — replace just the marker span.
            pattern2 = re.compile(re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK), re.DOTALL)
            new_text = pattern2.sub(block.split("\n", 1)[1] if False else block, original)
        _finish(readme, original, new_text, rel, result, write, bucket="modified")
        return

    lines = original.splitlines()

    # 2) Find an existing run section.
    header_idx = next((i for i, ln in enumerate(lines) if RUN_HEADER_RE.match(ln)), None)
    if header_idx is not None:
        end_idx = find_section_span(lines, header_idx)
        section = lines[header_idx:end_idx]
        if section_is_curated(section, runner_for(rel)):
            reason = "curated run section (mount / sub-steps / non-default runner)"
            result.special_skipped.append((rel, reason))
            return
        # Simple section -> replace in place.
        new_lines = lines[:header_idx] + block.splitlines() + lines[end_idx:]
        new_text = "\n".join(new_lines)
        if original.endswith("\n"):
            new_text += "\n"
        _finish(readme, original, new_text, rel, result, write, bucket="modified")
        return

    # 3) No run section -> insert before the first H2 (or at EOF).
    idx = intro_insert_idx(lines)
    insert = block.splitlines() + [""]
    new_lines = lines[:idx] + insert + lines[idx:]
    new_text = "\n".join(new_lines)
    if original.endswith("\n"):
        new_text += "\n"
    _finish(readme, original, new_text, rel, result, write, bucket="inserted_new")


def _finish(readme, original, new_text, rel, result, write, bucket):
    # Guarantee a blank line between the end marker and an immediately-following heading.
    new_text = new_text.replace(END_MARK + "\n#", END_MARK + "\n\n#")
    if new_text == original:
        result.unchanged.append(rel)
        return
    if write:
        readme.write_text(new_text, encoding="utf-8")
    getattr(result, bucket).append(rel)


# --- Main -------------------------------------------------------------------------------


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="dry-run; report without writing")
    args = ap.parse_args()
    write = not args.check

    readmes = sorted(
        p
        for p in EXAMPLES_ROOT.glob("0*-*/*/README.md")
        if re.match(r"^\d", p.parent.name) and (p.parent / "config.yaml").is_file()
    )
    result = Result()
    for readme in readmes:
        process(readme, result, write)

    print(f"Scanned {len(readmes)} numbered example READMEs\n")
    print(f"  modified (run section upgraded/refreshed): {len(result.modified)}")
    print(f"  inserted new section:                      {len(result.inserted_new)}")
    print(f"  unchanged (already conforming):            {len(result.unchanged)}")
    print(f"  vitrines skipped (curated by hand):        {len(result.vitrine_skipped)}")
    print(f"  special/curated skipped:                   {len(result.special_skipped)}")
    if result.special_skipped:
        print("\nSpecial / curated (left untouched — handle manually):")
        for rel, reason in result.special_skipped:
            print(f"  - {rel}: {reason}")
    if result.inserted_new:
        print("\nInserted brand-new section:")
        for rel in result.inserted_new:
            print(f"  - {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
