namespace Orkeon.Application.Rag;

/// <summary>
/// Represents a structured query for the RAG pipeline.
/// </summary>
public record RagQuery
{
    /// <summary>
    /// The question to answer using retrieved knowledge.
    /// </summary>
    public string Question { get; init; } = string.Empty;

    /// <summary>
    /// Optional additional context for the query.
    /// </summary>
    public string? Context { get; init; }

    /// <summary>
    /// Options controlling retrieval, augmentation, and generation.
    /// </summary>
    public RagOptions Options { get; init; } = new();

    /// <summary>
    /// Additional metadata associated with the query.
    /// </summary>
    public Dictionary<string, object> Metadata { get; init; } = [];
}

/// <summary>
/// Result of a RAG pipeline execution, including the answer, sources, and metrics.
/// </summary>
public record RagResult
{
    /// <summary>
    /// The generated answer text.
    /// </summary>
    public string Answer { get; init; } = string.Empty;

    /// <summary>
    /// The source chunks used to generate the answer.
    /// </summary>
    public IReadOnlyList<RetrievedChunk> Sources { get; init; } = Array.Empty<RetrievedChunk>();

    /// <summary>
    /// Performance and usage metrics for the pipeline execution.
    /// </summary>
    public RagMetrics Metrics { get; init; } = new();

    /// <summary>
    /// Indicates whether the answer is grounded in at least one source.
    /// </summary>
    public bool IsGrounded => Sources.Count > 0;
}

/// <summary>
/// A chunk of text retrieved from a knowledge source with relevance scoring.
/// </summary>
public record RetrievedChunk
{
    /// <summary>
    /// The text content of the chunk.
    /// </summary>
    public string Content { get; init; } = string.Empty;

    /// <summary>
    /// Identifier of the source this chunk came from.
    /// </summary>
    public string SourceId { get; init; } = string.Empty;

    /// <summary>
    /// Relevance score of this chunk to the query (0.0 to 1.0).
    /// </summary>
    public float RelevanceScore { get; init; }

    /// <summary>
    /// Additional metadata about the chunk.
    /// </summary>
    public Dictionary<string, object> Metadata { get; init; } = [];
}

/// <summary>
/// Metrics collected during RAG pipeline execution.
/// </summary>
public record RagMetrics
{
    /// <summary>
    /// Total number of chunks retrieved from knowledge sources.
    /// </summary>
    public int TotalChunksRetrieved { get; init; }

    /// <summary>
    /// Number of chunks actually included in the prompt.
    /// </summary>
    public int ChunksUsedInPrompt { get; init; }

    /// <summary>
    /// Average relevance score across all retrieved chunks.
    /// </summary>
    public float AverageRelevanceScore { get; init; }

    /// <summary>
    /// Time spent on the retrieval step.
    /// </summary>
    public TimeSpan RetrievalTime { get; init; }

    /// <summary>
    /// Time spent on the generation step.
    /// </summary>
    public TimeSpan GenerationTime { get; init; }

    /// <summary>
    /// Total end-to-end time for the pipeline.
    /// </summary>
    public TimeSpan TotalTime { get; init; }

    /// <summary>
    /// Total tokens consumed by the LLM during generation.
    /// </summary>
    public int TokensUsed { get; init; }
}

/// <summary>
/// An augmented prompt combining system instructions, user question, and retrieved context.
/// </summary>
public record AugmentedPrompt
{
    /// <summary>
    /// The system prompt providing instructions to the LLM.
    /// </summary>
    public string SystemPrompt { get; init; } = string.Empty;

    /// <summary>
    /// The user prompt containing context and question.
    /// </summary>
    public string UserPrompt { get; init; } = string.Empty;

    /// <summary>
    /// The chunks that were included in the prompt.
    /// </summary>
    public IReadOnlyList<RetrievedChunk> UsedChunks { get; init; } = Array.Empty<RetrievedChunk>();

    /// <summary>
    /// Estimated token count for the combined prompt.
    /// </summary>
    public int EstimatedTokens { get; init; }
}

/// <summary>
/// Response generated by an LLM.
/// </summary>
public record GeneratedResponse
{
    /// <summary>
    /// The generated text.
    /// </summary>
    public string Text { get; init; } = string.Empty;

    /// <summary>
    /// Number of tokens consumed.
    /// </summary>
    public int TokensUsed { get; init; }

    /// <summary>
    /// The model that produced the response.
    /// </summary>
    public string? Model { get; init; }
}
