using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;

namespace Orkeon.Scripting.Cli.Commands.Forge;

/// <summary>
/// The deterministic <c>.ork.ts</c> render (SPEC-ORKEON-FORGE §8.2): blueprint →
/// <c>crew/crew.ork.ts</c>, version directive first, <c>globalThis.crew =
/// crewBuilder()…build()</c> published the way <c>ScriptHost.LoadCrewFromFileAsync</c>
/// expects. The script is the **scripted equivalent of the YAML crew** — an editable
/// starting point, not conditional logic — and it is deliberately TypeScript-compatible
/// plain JavaScript: no type annotations, so the round-trip test can reload it without
/// esbuild while `orkeon run` still puts it through the real toolchain.
/// </summary>
internal static class ForgeScriptRenderer
{
    /// <summary>File name of the rendered script, inside the crew directory.</summary>
    public const string ScriptFileName = "crew.ork.ts";

    /// <summary>
    /// String literals are JSON-escaped — valid JavaScript by construction — with relaxed
    /// escaping: the file is meant to be read and edited by the crew's owner, and the
    /// conversation is French; <c>é</c> must stay <c>é</c>, not become <c>é</c>.
    /// </summary>
    private static readonly JsonSerializerOptions LiteralOptions = new()
    {
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    /// <summary>
    /// Renders <paramref name="blueprint"/> under <c>&lt;session&gt;/crew/</c>, replacing
    /// whatever was there — same stale-entity policy as the YAML render: a re-render never
    /// leaves files from the previous shape of the team. Returns the written relative paths.
    /// </summary>
    public static IReadOnlyList<string> Render(ForgeBlueprint blueprint, string sessionDirectory)
    {
        ArgumentNullException.ThrowIfNull(blueprint);
        ArgumentException.ThrowIfNullOrWhiteSpace(sessionDirectory);

        var crewDirectory = Path.Combine(sessionDirectory, ForgeYamlRenderer.CrewDirectoryName);
        if (Directory.Exists(crewDirectory))
            Directory.Delete(crewDirectory, recursive: true);
        Directory.CreateDirectory(crewDirectory);

        var identifiers = MintIdentifiers(blueprint);
        var script = new StringBuilder();
        script.Append("/// <reference orkeon-script=\"1.0\" />\n");
        script.Append("// Generated by Orkeon Forge — the scripted equivalent of the YAML crew: same\n");
        script.Append("// blueprint, same validator. An editable starting point, not conditional logic.\n");

        foreach (var agent in blueprint.Agents ?? [])
            AppendAgent(script, agent, identifiers);

        foreach (var task in OrderByDependencies(blueprint.Tasks ?? []))
            AppendTask(script, task, identifiers);

        AppendCrew(script, blueprint, identifiers);

        var relative = Path.Combine(ForgeYamlRenderer.CrewDirectoryName, ScriptFileName);
        File.WriteAllText(Path.Combine(sessionDirectory, relative), script.ToString());
        return [relative];
    }

    private static void AppendAgent(
        StringBuilder script, ForgeBlueprintAgent agent, Dictionary<string, string> identifiers)
    {
        script.Append('\n');
        script.Append("const ").Append(identifiers[AgentKey(agent.Key!)]).Append(" = agentBuilder()\n");
        script.Append("    .name(").Append(Literal(agent.Key!)).Append(")\n");
        script.Append("    .role(").Append(Literal(agent.Role ?? "")).Append(")\n");
        script.Append("    .goal(").Append(Literal(agent.Goal ?? "")).Append(")\n");
        if (!string.IsNullOrWhiteSpace(agent.Backstory))
            script.Append("    .backstory(").Append(Literal(agent.Backstory)).Append(")\n");
        if (agent.Tools is { Count: > 0 } tools)
        {
            script.Append("    .tools([")
                .Append(string.Join(", ", tools.Select(Literal)))
                .Append("])\n");
        }

        if (agent.AllowDelegation is { } delegation)
            script.Append("    .allowDelegation(").Append(delegation ? "true" : "false").Append(")\n");
        if (agent.MaxIterations is { } iterations)
            script.Append("    .maxIterations(").Append(iterations).Append(")\n");
        script.Append("    .build();\n");
    }

    private static void AppendTask(
        StringBuilder script, ForgeBlueprintTask task, Dictionary<string, string> identifiers)
    {
        script.Append('\n');
        script.Append("const ").Append(identifiers[TaskKey(task.Key!)]).Append(" = taskBuilder()\n");
        script.Append("    .name(").Append(Literal(task.Key!)).Append(")\n");
        script.Append("    .description(").Append(Literal(task.Description ?? "")).Append(")\n");
        script.Append("    .expectedOutput(").Append(Literal(task.ExpectedOutput ?? "")).Append(")\n");
        if (task.Agent is not null && identifiers.TryGetValue(AgentKey(task.Agent), out var agentIdentifier))
            script.Append("    .agent(").Append(agentIdentifier).Append(")\n");
        foreach (var dependency in task.Dependencies ?? [])
        {
            if (identifiers.TryGetValue(TaskKey(dependency), out var dependencyIdentifier))
                script.Append("    .withContext(").Append(dependencyIdentifier).Append(")\n");
        }

        if (!string.IsNullOrWhiteSpace(task.Deliverable))
            script.Append("    .deliverable({ path: ").Append(Literal(task.Deliverable)).Append(" })\n");
        script.Append("    .build();\n");
    }

    private static void AppendCrew(
        StringBuilder script, ForgeBlueprint blueprint, Dictionary<string, string> identifiers)
    {
        script.Append('\n');
        if (blueprint.Crew?.Memory == true)
        {
            // Never a silent drop: memory has no scripting surface, so the fact is kept
            // in front of the person who will edit this file.
            script.Append("// The blueprint asked for crew memory; the scripting DSL has no memory\n");
            script.Append("// surface yet — configure a memory provider on the host (appsettings) instead.\n");
        }

        script.Append("globalThis.crew = crewBuilder()\n");
        script.Append("    .name(").Append(Literal(blueprint.Crew?.Name ?? "")).Append(")\n");
        script.Append("    .goal(").Append(Literal(blueprint.Crew?.Goal ?? "")).Append(")\n");
        if (!string.IsNullOrWhiteSpace(blueprint.Crew?.Process))
            script.Append("    .process(").Append(Literal(blueprint.Crew.Process)).Append(")\n");
        if (blueprint.Crew?.Verbose == true)
            script.Append("    .verbose(true)\n");

        foreach (var agent in blueprint.Agents ?? [])
            script.Append("    .withAgent(").Append(identifiers[AgentKey(agent.Key!)]).Append(")\n");
        foreach (var task in blueprint.Tasks ?? [])
            script.Append("    .withTask(").Append(identifiers[TaskKey(task.Key!)]).Append(")\n");
        if (blueprint.Manager is not null && identifiers.TryGetValue(AgentKey(blueprint.Manager), out var manager))
            script.Append("    .manager(").Append(manager).Append(")\n");
        script.Append("    .build();\n");
    }

    /// <summary>
    /// One identifier per entity, agents and tasks in separate namespaces (an agent and a
    /// task may share a key). Sanitizing can merge two distinct keys (<c>a-b</c> / <c>a_b</c>);
    /// a numeric suffix keeps the render deterministic instead of producing a broken script.
    /// </summary>
    private static Dictionary<string, string> MintIdentifiers(ForgeBlueprint blueprint)
    {
        var identifiers = new Dictionary<string, string>(StringComparer.Ordinal);
        var taken = new HashSet<string>(StringComparer.Ordinal);

        foreach (var agent in blueprint.Agents ?? [])
        {
            if (agent.Key is not null)
                identifiers[AgentKey(agent.Key)] = Mint("agent_", agent.Key, taken);
        }

        foreach (var task in blueprint.Tasks ?? [])
        {
            if (task.Key is not null)
                identifiers[TaskKey(task.Key)] = Mint("task_", task.Key, taken);
        }

        return identifiers;
    }

    private static string Mint(string prefix, string key, HashSet<string> taken)
    {
        var sanitized = new string([.. key.Select(c => char.IsAsciiLetterOrDigit(c) ? c : '_')]);
        var identifier = prefix + sanitized;
        var suffix = 2;
        while (!taken.Add(identifier))
            identifier = string.Create(System.Globalization.CultureInfo.InvariantCulture, $"{prefix}{sanitized}_{suffix++}");
        return identifier;
    }

    private static string AgentKey(string key) => "agent " + key;

    private static string TaskKey(string key) => "task " + key;

    /// <summary>
    /// Emits tasks so that every <c>withContext</c> reference points at an already-declared
    /// const (Kahn's ordering). A cyclic blueprint cannot be ordered — the remaining tasks
    /// keep their blueprint order and the shared validator rejects the cycle right after;
    /// the render itself never crashes.
    /// </summary>
    private static List<ForgeBlueprintTask> OrderByDependencies(IReadOnlyList<ForgeBlueprintTask> tasks)
    {
        var ordered = new List<ForgeBlueprintTask>(tasks.Count);
        var emitted = new HashSet<string>(StringComparer.Ordinal);
        var remaining = new List<ForgeBlueprintTask>(tasks);

        while (remaining.Count > 0)
        {
            var progressed = false;
            for (var i = 0; i < remaining.Count; i++)
            {
                var task = remaining[i];
                var dependencies = task.Dependencies ?? [];
                if (!dependencies.All(d => emitted.Contains(d) || tasks.All(t => t.Key != d)))
                    continue;

                ordered.Add(task);
                if (task.Key is not null)
                    emitted.Add(task.Key);
                remaining.RemoveAt(i--);
                progressed = true;
            }

            if (!progressed)
            {
                ordered.AddRange(remaining);
                break;
            }
        }

        return ordered;
    }

    private static string Literal(string value) => JsonSerializer.Serialize(value, LiteralOptions);
}
