using Microsoft.Extensions.AI;
using System.Text.RegularExpressions;
using Orkeon.Domain.Flows;
using Orkeon.Domain.Flows.ValueObjects;
using Orkeon.Infrastructure.Flows.Base;

namespace Orkeon.Infrastructure.Flows.Steps;

/// <summary>Typed input for <see cref="LlmFlowStep"/>. Captures runtime context for template resolution.</summary>
public sealed class LlmFlowStepInput
{
    /// <summary>Optional runtime override for the prompt template.</summary>
    public string? PromptTemplate { get; set; }

    /// <summary>Optional runtime override for the system prompt.</summary>
    public string? SystemPrompt { get; set; }
}

/// <summary>Typed output for <see cref="LlmFlowStep"/>.</summary>
public sealed class LlmFlowStepOutput
{
    /// <summary>Gets or sets the text response generated by the LLM.</summary>
    public string LlmResponse { get; set; } = string.Empty;
}

/// <summary>
/// Flow step that calls an LLM using IChatClient from Microsoft.Extensions.AI.
/// </summary>
public partial class LlmFlowStep : FlowStepBase<LlmFlowStepInput, LlmFlowStepOutput>
{
    private readonly IChatClient _chatClient;
    private readonly FlowStepParameters _parameters;
    private readonly string _name;

    // We keep a reference to the original FlowState for template resolution.
    // The base class converts FlowState → typed input, but we also need the raw context for template vars.
    private FlowState? _currentContext;

    /// <inheritdoc />
    public override string Name => _name;
    /// <inheritdoc />
    public override string Description => "Executes an LLM prompt and returns the response.";

    /// <summary>Initializes a new instance of <see cref="LlmFlowStep"/>.</summary>
    /// <param name="name">The step name.</param>
    /// <param name="parameters">The step parameters.</param>
    /// <param name="chatClient">The chat client for LLM calls.</param>
    public LlmFlowStep(
        string name,
        FlowStepParameters parameters,
        IChatClient chatClient)
    {
        _name = name;
        _parameters = parameters;
        ArgumentNullException.ThrowIfNull(chatClient);
        _chatClient = chatClient;
    }

    /// <inheritdoc />
    public override IReadOnlyList<string> Dependencies => Array.Empty<string>();

    /// <summary>
    /// Override ExecuteAsync to capture the raw FlowState for template resolution
    /// before delegating to the base typed pipeline.
    /// </summary>
    public override async Task<FlowStepResult> ExecuteAsync(FlowState context, CancellationToken cancellationToken = default)
    {
        _currentContext = context;
        try
        {
            return await base.ExecuteAsync(context, cancellationToken).ConfigureAwait(false);
        }
        finally
        {
            _currentContext = null;
        }
    }

    /// <inheritdoc />
    protected override string? ValidateTypedRequest(LlmFlowStepInput request)
    {
        ArgumentNullException.ThrowIfNull(request);
        var promptTemplate = _parameters.Get<string>("prompt_template") ?? request.PromptTemplate;
        return string.IsNullOrEmpty(promptTemplate) ? "Missing 'prompt_template' parameter." : null;
    }

    /// <inheritdoc />
    protected override Task<LlmFlowStepOutput> ExecuteTypedAsync(
        LlmFlowStepInput request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        return ExecuteTypedCoreAsync();

        async Task<LlmFlowStepOutput> ExecuteTypedCoreAsync()
        {
            var promptTemplate = _parameters.Get<string>("prompt_template") ?? request.PromptTemplate
                ?? throw new InvalidOperationException("Missing 'prompt_template' parameter.");

            // Resolve template variables from context
            var resolvedPrompt = _currentContext is not null
                ? ResolveTemplate(promptTemplate, _currentContext)
                : promptTemplate;

            var messages = new List<ChatMessage>
            {
                new(ChatRole.User, resolvedPrompt)
            };

            // Check for system prompt from parameters or runtime context
            var systemPrompt = _parameters.Get<string>("system_prompt") ?? request.SystemPrompt;
            if (!string.IsNullOrEmpty(systemPrompt))
            {
                messages.Insert(0, new ChatMessage(ChatRole.System, systemPrompt));
            }

            var response = await _chatClient.GetResponseAsync(messages, cancellationToken: cancellationToken).ConfigureAwait(false);
            var responseText = response?.Text ?? string.Empty;

            return new LlmFlowStepOutput
            {
                LlmResponse = responseText
            };
        }
    }

    /// <summary>
    /// Resolves template variables in the form {key} or {step.output} from context.
    /// </summary>
    /// <param name="template">The template string containing variable placeholders.</param>
    /// <param name="context">The flow state providing variable values.</param>
    /// <returns>The template with all resolved variable placeholders replaced.</returns>
    public static string ResolveTemplate(string template, FlowState context)
    {
        return TemplateVariableRegex().Replace(template, match =>
        {
            var key = match.Groups[1].Value;
            var value = context.Get<object>(key);
            return value?.ToString() ?? match.Value;
        });
    }

    [GeneratedRegex(@"\{(\w+(?:\.\w+)*)\}")]
    private static partial Regex TemplateVariableRegex();
}
